# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17267e8dcb7ab1fe1e288cc57d1a49bc59913a4e658d864e2d3ca9644d552e7a3e9aa2e88a56d1a48b0559dd338226ea699aee85589d5cf1989d397a41798037

test:
  secret_key_base: 54cf2a050800b73eee9f129f1dbc27e874d488bdf1088905fccfaf69efdb9803fc7f18f94db8659f4a8e90ea49a3af9df223571c9060067d38b2e2ec9e6de8c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
